###hadoop
hadoop:
  image: anair/hadoop:2.7.1
  container_name: hadoop
  hostname: hadoop
  ports:
    - "49707:49707"
    - "50010:50010"
    - "50020:50020"
    - "50030:50030" 
    - "50070:50070"
    - "50075:50075"
    - "50090:50090"
    - "8030:8030"
    - "8031:8031"
    - "8032:8032"
    - "8033:8033"
    - "8040:8040"
    - "8042:8042"
    - "8088:8088"

###zookeeper
zookeeper:
  image: anair/zookeeper:3.4.6
  container_name: zookeeper
  hostname: zk
  ports:
    - "2181:2181"

###hbase
hbase:
   image: anair/hbase:1.1.2
   container_name: hbase
   hostname: hbase
   ports:
     - "60000:60000"
     - "60010:60010"
     - "60020:60020"
     - "60030:60030"
   links:
     - zookeeper:zk

###kafka
kafka:
  image: anair/kafka:0.8.2
  container_name: kafka
  hostname: kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.56.102
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BROKER_ID: 0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

###Storm
nimbus:
  image: anair/storm-nimbus:0.10.0
  container_name: storm-nimbus
  hostname: nimbus   
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk

supervisor:
  image: anair/storm-supervisor:0.10.0
  container_name: storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk

ui:
  image: anair/storm-ui:0.10.0
  container_name: storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
